pipeline {
    agent any

    stages {
        stage('Maven build') {
            // Demander à Jenkins d'exécuter le builder dans un container Docker
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    // args '''
                    //     -v $HOME/.m2:/root/.m2:z
                    //     -u root
                    //     --network devops
                    // ''' // On se place sur le réseau devops pour pouvoir contacter sonar !
                    args '--network devops'
                    reuseNode true // Permet de garder le même workspace entre les différents agents (any & docker)
                }
            }

            steps {
                dir('bibliotek-boot') {
                    withSonarQubeEnv('sonarqube') {
                        sh "mvn verify sonar:sonar -Dsonar.projectKey=bibliotek-boot -Dsonar.projectName='bibliotek-boot'"
                    }
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker build') {
            steps {
                dir('bibliotek-boot') {
                    sh 'docker build -t bibliotek-boot .'
                }
            }
        }

        stage('Docker deploy') {
            steps {
                sh 'docker compose up -d --no-deps boot'
            }
        }
    }
}