pipeline {
    agent any

    stages {
        stage('Build') {
            // Demander à Jenkins d'exécuter le builder dans un container Docker
            agent {
                docker {
                    image 'node:lts-bullseye'
                    // args '''
                    //     -v $HOME/.npm:/root/.npm:z
                    //     -u root
                    // '''
                    args '--network devops'
                    reuseNode true // Permet de garder le même workspace entre les différents agents (any & docker)
                }
            }

            stages {
                stage('Install dependencies') {
                    steps {
                        sh 'npm install'
                    }
                }

                stage('Sonar analysis') {
                    steps {
                        sh './node_modules/.bin/sonar-scanner -Dsonar.projectKey=bilbiotek-angular'
                    }
                }

                stage('NPM Build') {
                    steps {
                        sh './node_modules/.bin/ng build'
                    }
                }
            }
        }

        stage('Docker build') {
            steps {
                sh 'docker build -t bilbiotek-angular .'
            }
        }

        stage('Docker deploy') {
            steps {
                dir('..') {
                    sh 'docker compose up -d --no-deps web'
                }
            }
        }
    }
}